export const SlidesFakeData = [
  {
    image: "",
    slide: 1,
    cytomine: "",
    laboratory: "",
    testNumber: 0,
    testType: "",
    progress: "",
    // durations: [],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 2,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 550036,
    testType: "CC",
    progress: "scanned",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
      {
        id: 3,
        magnification: "40x",
        duration: 5,
      },
    ],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 3,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 550037,
    testType: "CC",
    progress: "scanned",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
      {
        id: 3,
        magnification: "40x",
        duration: 5,
      },
    ],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 4,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 550038,
    testType: "CC",
    progress: "ready",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 5,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 550039,
    testType: "CC",
    progress: "scanned",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 6,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 550040,
    testType: "CC",
    progress: "failed",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 7,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 550041,
    testType: "CC",
    progress: "ready",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 8,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 550042,
    testType: "CC",
    progress: "ready",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 9,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 550043,
    testType: "CC",
    progress: "ready",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    image: "/media/slides/slide1.png",
    slide: 10,
    cytomine: "",
    laboratory: "Milad",
    testNumber: 0,
    testType: "CC",
    progress: "ready",
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
];

export const imgURL1 =
  "http://magic.deepdream.ir/#/project/44973/image/45407/slice/45408?viewer=faf05z19e";

export const imgURL2 =
  "http://magic.deepdream.ir/#/project/44973/image/45448/slice/45449?viewer=rspvwop20";

export const imgURL3 =
  "http://magic.deepdream.ir/#/project/44973/image/45487/slice/45488?viewer=gy38kob63";

export const FAKE_DATA = [
  {
    name: "Azam Ghasemi",
    date: "1402-10-01 10:12",
    id: 10,
    number: 86203,
    nationalId: 1234567890,
    img: imgURL1,
    labNumber: "C02-4788",
    testType: "PBS",
    age: 35,
    sex: "Female",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Nobel",
    progress: "scanned",
    price: 120000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
      {
        id: 3,
        magnification: "40x",
        duration: 10,
      },
      {
        id: 4,
        magnification: "100x",
        duration: 30,
      },
    ],
  },
  {
    name: "Razieh Aabedini",
    date: "1402-10-01 13:05",
    labNumber: "C02-4786",
    id: 9,
    number: 56001,
    nationalId: 1234567890,
    img: imgURL2,
    testType: "Papsmear",
    age: 37,
    sex: "Female",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Nobel",
    progress: "answered",
    price: 120000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    name: "Lotfallah Moradi",
    date: "1402-10-03 11:00",
    labNumber: "S02-49",
    id: 8,
    number: 67201,
    nationalId: 1234567890,
    img: imgURL3,
    testType: "Gastric",
    age: 72,
    sex: "Male",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Arya",
    progress: "deleted",
    price: 630000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    name: "Mehri Alaafchian",
    date: "1402-10-04 18:31",
    labNumber: "C02-4784",
    id: 7,
    number: 45404,
    nationalId: 1234567890,
    testType: "TAH",
    age: 68,
    sex: "Female",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Erythron",
    progress: "confirmed",
    price: 700000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    name: "Ellaheh Habibi",
    date: "1402-10-06 10:27",
    labNumber: "C02-4680",
    id: 6,
    number: 70008,
    nationalId: 1234567890,
    testType: "Colon",
    age: 31,
    sex: "Female",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Milad",
    progress: "scanning",
    price: 450000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    name: "Mina Ahmadi",
    date: "1402-10-07 20:05",
    labNumber: "P02-703",
    id: 5,
    number: 69023,
    nationalId: 1234567890,
    testType: "Breast",
    age: 45,
    sex: "Female",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Erythron",
    progress: "new",
    price: 500000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    name: "Fatemeh Bagherian",
    date: "1402-09-29 10:50",
    labNumber: "P02-697",
    id: 4,
    number: 67541,
    nationalId: 1234567890,
    testType: "Colon",
    age: 63,
    sex: "Female",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Milad",
    progress: "new",
    price: 450000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    name: "Ebrahim Salehi",
    date: "1402-09-20 10:50",
    labNumber: "P02-691",
    id: 3,
    number: 59173,
    nationalId: 1234567890,
    testType: "Gastric",
    age: 63,
    sex: "Male",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Milad",
    progress: "answered",
    price: 630000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    name: "Taghi Kianian",
    date: "1402-08-10 10:50",
    labNumber: "P02-652",
    id: 2,
    number: 75861,
    nationalId: 1234567890,
    testType: "PBS",
    age: 35,
    sex: "Male",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Milad",
    progress: "scanning",
    price: 170000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
  {
    name: "Ebrahim Shahriari",
    date: "1402-07-19 10:50",
    labNumber: "P02-593",
    id: 1,
    number: 1,
    nationalId: 1234567890,
    testType: "Colon",
    age: 41,
    sex: "Male",
    description:
      "Description is any type of communication that aims to make vivid a place, object, person, group, or other physical entity. Description is one of four rhetorical modes, along with exposition, argumentation, and narration.",
    laboratory: "Milad",
    progress: "Scanned",
    price: 450000,
    numberOfSlides: 1,
    durations: [
      {
        id: 1,
        magnification: "2x",
        duration: 2,
      },
      {
        id: 2,
        magnification: "10x",
        duration: 3,
      },
    ],
  },
];

export const LABS_TESTS_DATA = [
  {
    id: 1,
    labName: "Nobel",
    fullName: "Ali Ahmadi",
    phone: "09100520741",
    address: "Esfahan,Bozorgmehr st. 15",
    description: "description for laboratories",
    username: "username",
    picture: "avatars/300-6.jpg",
    totalTests: Math.floor(Math.random() * (90 - 10 + 1)),
    totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
    tests: [
      {
        id: 12,
        testName: "Breast",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 13,
        testName: "Papsmear",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 14,
        testName: "PBS",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 15,
        testName: "Colon",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 16,
        testName: "Gastric",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 17,
        testName: "TAH",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
    ],
  },
  {
    id: 2,
    labName: "Milad",
    fullName: "Ali Ahmadi",
    phone: "09100520741",
    address: "Esfahan,Bozorgmehr st. 15",
    description: "description for laboratories",
    username: "username",
    picture: "avatars/300-1.jpg",
    totalTests: Math.floor(Math.random() * (90 - 10 + 1)),
    totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
    tests: [
      {
        id: 12,
        testName: "Breast",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 13,
        testName: "Papsmear",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 14,
        testName: "PBS",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 15,
        testName: "Colon",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 16,
        testName: "Gastric",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 17,
        testName: "TAH",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
    ],
  },
  {
    id: 3,
    labName: "Arya",
    fullName: "Ali Ahmadi",
    phone: "09100520741",
    address: "Esfahan,Bozorgmehr st. 15",
    description: "description for laboratories",
    username: "username",
    picture: "avatars/300-1.jpg",
    totalTests: Math.floor(Math.random() * (90 - 10 + 1)),
    totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
    tests: [
      {
        id: 12,
        testName: "Breast",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 13,
        testName: "Papsmear",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 14,
        testName: "PBS",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 15,
        testName: "Colon",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 16,
        testName: "Gastric",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 17,
        testName: "TAH",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
    ],
  },
  {
    id: 4,
    labName: "Erythron",
    fullName: "Ali Ahmadi",
    phone: "09100520741",
    address: "Esfahan,Bozorgmehr st. 15",
    description: "description for laboratories",
    username: "username",
    picture: "avatars/300-1.jpg",
    totalTests: Math.floor(Math.random() * (90 - 10 + 1)),
    totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
    tests: [
      {
        id: 12,
        testName: "Breast",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 13,
        testName: "Papsmear",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 14,
        testName: "PBS",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 15,
        testName: "Colon",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 16,
        testName: "Gastric",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 17,
        testName: "TAH",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
    ],
  },
  {
    id: 5,
    labName: "Baradaran",
    fullName: "Ali Ahmadi",
    phone: "09100520741",
    address: "Esfahan,Bozorgmehr st. 15",
    description: "description for laboratories",
    username: "username",
    picture: "avatars/300-1.jpg",
    totalTests: Math.floor(Math.random() * (90 - 10 + 1)),
    totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
    tests: [
      {
        id: 12,
        testName: "Breast",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 13,
        testName: "Papsmear",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 14,
        testName: "PBS",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 15,
        testName: "Colon",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 16,
        testName: "Gastric",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
      {
        id: 17,
        testName: "TAH",
        testPrice: 25000,
        description: "test type price test description",
        testExtraPrice: 10000,
        totalNamber: Math.floor(Math.random() * (90 - 10 + 1)),
        totalPrice: Math.floor(Math.random() * (900000 - 100000 + 1)) + 100000,
      },
    ],
  },
];

export const counsellorsData = [
  {
    id: 1,
    labName: "Milad",
    name: "Dr. Ahmadi",
    phone: "09100520741",
  },
  {
    id: 2,
    labName: "Milad",
    name: "Dr. Sadeghi",
    phone: "09100520741",
  },
  {
    id: 3,
    labName: "Milad",
    name: "Dr. Nasr",
    phone: "09100520741",
  },
  {
    id: 4,
    labName: "Milad",
    name: "Dr. Fard",
    phone: "09100520741",
  },
  {
    id: 5,
    labName: "Milad",
    name: "Dr. Fard",
    phone: "09100520741",
  },
  {
    id: 6,
    labName: "Milad",
    name: "Dr. Fard",
    phone: "09100520741",
  },
  {
    id: 7,
    labName: "Milad",
    name: "Dr. Fard",
    phone: "09100520741",
  },
];

export const TEST_TYPES = [
  {
    id: 12,
    title: "Breast",
    code: 120,
    sex: "male",
    description: "test description to clarify darkness points.",
    type: "optical",
    numberOfLayers: 1,
    z: 1,
    condenseur: 2,
    brightness: 3,
    magnifications: [1, 2],
    prices: [
      {
        id: 1,
        lab: {
          id: 1,
          name: "Milad",
        },
        price: 25000,
      },
      {
        id: 2,
        lab: {
          id: 2,
          name: "Ariya",
        },
        price: 15000,
      },
      {
        id: 3,
        lab: {
          id: 3,
          name: "Nobel",
        },
        price: 35000,
      },
      {
        id: 4,
        lab: {
          id: 4,
          name: "Shargh",
        },
        price: 25000,
      },
    ],
  },
  {
    id: 13,
    title: "Papsmear",
    code: 121,
    sex: "male",
    description: "test description to clarify darkness points.",
    type: "optical",
    numberOfLayers: 1,
    z: 1,
    condenseur: 2,
    brightness: 3,
    magnifications: [3, 2],
    prices: [
      {
        id: 1,
        lab: {
          id: 1,
          name: "Milad",
        },
        price: 25000,
      },
      {
        id: 2,
        lab: {
          id: 2,
          name: "Ariya",
        },
        price: 15000,
      },
      {
        id: 3,
        lab: {
          id: 3,
          name: "Nobel",
        },
        price: 35000,
      },
      {
        id: 4,
        lab: {
          id: 4,
          name: "Shargh",
        },
        price: 25000,
      },
    ],
  },
  {
    id: 14,
    title: "PBS",
    code: 122,
    sex: "male",
    description: "test description to clarify darkness points.",
    type: "Flourscent",
    numberOfLayers: 1,
    z: 1,
    condenseur: 2,
    brightness: 3,
    magnifications: [1, 3],
    prices: [
      {
        id: 1,
        lab: {
          id: 1,
          name: "Milad",
        },
        price: 25000,
      },
      {
        id: 2,
        lab: {
          id: 2,
          name: "Ariya",
        },
        price: 15000,
      },
      {
        id: 3,
        lab: {
          id: 3,
          name: "Nobel",
        },
        price: 35000,
      },
      {
        id: 4,
        lab: {
          id: 4,
          name: "Shargh",
        },
        price: 25000,
      },
    ],
  },
  {
    id: 15,
    title: "Colon",
    code: 123,
    sex: "male",
    description: "test description to clarify darkness points.",
    type: "invert",
    numberOfLayers: 1,
    z: 1,
    condenseur: 2,
    brightness: 3,
    magnifications: [4, 2],
    prices: [
      {
        id: 1,
        lab: {
          id: 1,
          name: "Milad",
        },
        price: 25000,
      },
      {
        id: 2,
        lab: {
          id: 2,
          name: "Ariya",
        },
        price: 15000,
      },
      {
        id: 3,
        lab: {
          id: 3,
          name: "Nobel",
        },
        price: 35000,
      },
      {
        id: 4,
        lab: {
          id: 4,
          name: "Shargh",
        },
        price: 25000,
      },
    ],
  },
  {
    id: 16,
    title: "Gastric",
    code: 124,
    sex: "male",
    description: "test description to clarify darkness points.",
    type: "optical",
    numberOfLayers: 1,
    z: 1,
    condenseur: 2,
    brightness: 3,
    magnifications: [1, 2, 3],
    prices: [
      {
        id: 1,
        lab: {
          id: 1,
          name: "Milad",
        },
        price: 25000,
      },
      {
        id: 2,
        lab: {
          id: 2,
          name: "Ariya",
        },
        price: 15000,
      },
      {
        id: 3,
        lab: {
          id: 3,
          name: "Nobel",
        },
        price: 35000,
      },
      {
        id: 4,
        lab: {
          id: 4,
          name: "Shargh",
        },
        price: 25000,
      },
    ],
  },
  {
    id: 17,
    title: "TAH",
    code: 125,
    sex: "male",
    description: "test description to clarify darkness points.",
    type: "optical",
    numberOfLayers: 1,
    z: 1,
    condenseur: 2,
    brightness: 3,
    magnifications: [1, 2, 3, 4],
    prices: [
      {
        id: 1,
        lab: {
          id: 1,
          name: "Milad",
        },
        price: 25000,
      },
      {
        id: 2,
        lab: {
          id: 2,
          name: "Ariya",
        },
        price: 15000,
      },
      {
        id: 3,
        lab: {
          id: 3,
          name: "Nobel",
        },
        price: 35000,
      },
      {
        id: 4,
        lab: {
          id: 4,
          name: "Shargh",
        },
        price: 25000,
      },
    ],
  },
];

export const DEFAULT_SETTINGS = [
  {
    id: 1,
    title: "2x",
    settings: [
      {
        id: 1,
        title: "condenseur",
        value: 20,
        type: "number",
      },
      {
        id: 2,
        title: "brightness",
        value: 10,
        type: "number",
      },

      {
        id: 4,
        title: "microStep",
        value: 20,
        type: "number",
      },
      {
        id: 5,
        title: "x",
        value: 3,
        type: "number",
      },
      {
        id: 6,
        title: "y",
        value: 6,
        type: "number",
      },
      {
        id: 7,
        title: "z",
        value: 50,
        type: "number",
      },
    ],
  },
  {
    id: 2,
    title: "10x",
    settings: [
      {
        id: 1,
        title: "condenseur",
        value: 20,
        type: "number",
      },
      {
        id: 2,
        title: "brightness",
        value: 10,
        type: "number",
      },

      {
        id: 4,
        title: "microStep",
        value: 20,
        type: "number",
      },
      {
        id: 5,
        title: "x",
        value: 3,
        type: "number",
      },
      {
        id: 6,
        title: "y",
        value: 6,
        type: "number",
      },
      {
        id: 7,
        title: "z",
        value: 50,
        type: "number",
      },
    ],
  },
  {
    id: 3,
    title: "40x",
    settings: [
      {
        id: 1,
        title: "condenseur",
        value: 20,
        type: "number",
      },
      {
        id: 2,
        title: "brightness",
        value: 10,
        type: "number",
      },

      {
        id: 4,
        title: "microStep",
        value: 20,
        type: "number",
      },
      {
        id: 5,
        title: "x",
        value: 3,
        type: "number",
      },
      {
        id: 6,
        title: "y",
        value: 6,
        type: "number",
      },
      {
        id: 7,
        title: "z",
        value: 50,
        type: "number",
      },
    ],
  },
  {
    id: 4,
    title: "100x",
    settings: [
      {
        id: 1,
        title: "condenseur",
        value: 20,
        type: "number",
      },
      {
        id: 2,
        title: "brightness",
        value: 10,
        type: "number",
      },

      {
        id: 4,
        title: "microStep",
        value: 20,
        type: "number",
      },
      {
        id: 5,
        title: "x",
        value: 3,
        type: "number",
      },
      {
        id: 6,
        title: "y",
        value: 6,
        type: "number",
      },
      {
        id: 7,
        title: "z",
        value: 50,
        type: "number",
      },
    ],
  },
  {
    id: 5,
    title: "field lens placement",
    settings: [
      {
        id: 1,
        title: "2x",
        value: 20,
        type: "number",
      },
      {
        id: 2,
        title: "10x",
        value: 10,
        type: "number",
      },
      {
        id: 4,
        title: "40x",
        value: 20,
        type: "number",
      },
      {
        id: 5,
        title: "100x",
        value: 3,
        type: "number",
      },
    ],
  },
  {
    id: 6,
    title: "condenseur placement",
    settings: [
      {
        id: 1,
        title: "min",
        value: 20,
        type: "number",
      },
      {
        id: 2,
        title: "max",
        value: 10,
        type: "number",
      },
    ],
  },
];

export const Slides_Placements = [
  {
    id: 1,
    title: "slide 1",
    coordinates: [
      {
        id: 1,
        title: "x",
        value: 20,
      },
      {
        id: 2,
        title: "y",
        value: 0,
      },
    ],
  },
  {
    id: 2,
    title: "slide 2",
    coordinates: [
      {
        id: 1,
        title: "x",
        value: 20,
      },
      {
        id: 2,
        title: "y",
        value: 0,
      },
    ],
  },
];

export const BarChartTotalsNumber = [
  {
    title: "Total Tests",
    unit: "tests",
    value: LABS_TESTS_DATA.reduce((acc, lab) => acc + lab.totalTests, 0),
  },
  {
    title: "Date Range",
    unit: "",
    value: "All Time",
  },
];
export const BarChartTotalsPrice = [
  {
    title: "Total Price",
    unit: "(R)",
    value: LABS_TESTS_DATA.reduce(
      (acc, lab) => acc + lab.totalPrice,
      0
    ).toLocaleString(),
  },
  {
    title: "Range Date",
    unit: "",
    value: "All Time",
  },
];
export const testNumberSeries = [
  {
    name: "Total Tests",
    data: LABS_TESTS_DATA.map((lab) => lab.totalTests).sort((a, b) => b - a),
  },
];
export const testPriceSeries = [
  {
    name: "Total Price",
    data: LABS_TESTS_DATA.map((lab) => lab.totalPrice).sort((a, b) => b - a),
  },
];
export const xaxisCategories = LABS_TESTS_DATA.map((lab) => lab.labName);

export const radarPriceSeries = LABS_TESTS_DATA.map((lab) => {
  const testData = lab.tests.map((test) => test.totalPrice);
  return {
    name: lab.labName,
    data: testData,
  };
});
export const radarNumberSeries = LABS_TESTS_DATA.map((lab) => {
  const testData = lab.tests.map((test) => test.totalNamber);
  return {
    name: lab.labName,
    data: testData,
  };
});

export const xaxisTestTypeCategories = TEST_TYPES.map((test) => test.title);

export const TestTypeNumberSeries = [
  {
    name: "Total Tests",
    data: TEST_TYPES.map((test) =>
      LABS_TESTS_DATA.reduce(
        (accum, lab) =>
          accum +
          (lab.tests.find((labTest) => labTest.id === test.id)?.totalNamber ||
            0),
        0
      )
    ),
  },
];
export const TestTypePriceSeries = [
  {
    name: "Total Prices",
    data: TEST_TYPES.map((test) =>
      LABS_TESTS_DATA.reduce(
        (accum, lab) =>
          accum +
          (lab.tests.find((labTest) => labTest.id === test.id)?.totalPrice ||
            0),
        0
      )
    ),
  },
];

export const defaultAlerts = [
  {
    id: 7,
    name: "Dr. Ahmadi",
    description: "Made an annotation.",
    time: "1 hr",
    icon: "message-text-2",
    state: "primary",
  },
  {
    id: 6,
    name: "Dr. Soltani",
    description: "Made an annotation.",
    time: "2 hrs",
    icon: "message-text",
    state: "danger",
  },
  {
    id: 5,
    name: "Dr. Nasr",
    description: "Made an annotation.",
    time: "5 hrs",
    icon: "message-text",
    state: "warning",
  },
  // {
  //   id: 4,
  //   name: "Project Red",
  //   description: "Made an annotation.",
  //   time: "2 days",
  //   icon: "cloud-change",
  //   state: "success",
  // },
  // {
  //   id: 3,
  //   name: "Project Breafing",
  //   description: "Made an annotation.",
  //   time: "21 Jan",
  //   icon: "compass",
  //   state: "primary",
  // },
  // {
  //   id: 2,
  //   name: "Banner Assets",
  //   description: "Made an annotation.",
  //   time: "21 Jan",
  //   icon: "graph-3",
  //   state: "info",
  // },
  // {
  //   id: 1,
  //   name: "Icon Assets",
  //   description: "Made an annotation.",
  //   time: "20 March",
  //   icon: "color-swatch",
  //   state: "warning",
  // },
];

const jjj = {
  current_page: 1,
  data: [
    {
      id: 1,
      patient_id: 14,
      lab_id: 72,
      test_type_id: 13,
      sender_register_code: "226",
      doctor_name: "Dr. Ed Gerhold V",
      price: 62243,
      status: "registered",
      num_slide: 3,
      duration: 25,
      description:
        "Magnam harum voluptatum quasi et ut dolor autem facilis rerum.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 13,
        title: "ut",
        code: "452",
        gender: "female",
        type: "fluorescent",
        num_layer: 1,
        step: null,
        micro_step: null,
        z_axis: null,
        condenser: null,
        brightness: null,
        magnification: 2,
        description:
          "Voluptatem esse ipsa odit doloremque eveniet aliquam consectetur odio laborum quod et.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:09.000000Z",
        updated_at: "2024-01-24T13:55:09.000000Z",
      },
    },
    {
      id: 2,
      patient_id: 52,
      lab_id: 3,
      test_type_id: 20,
      sender_register_code: "638",
      doctor_name: "Mark Schultz",
      price: 111107,
      status: "answered",
      num_slide: 1,
      duration: 30,
      description:
        "Enim quis soluta quidem qui voluptatem autem numquam consectetur totam voluptas voluptatibus voluptatem.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 20,
        title: "sunt",
        code: "598",
        gender: "female",
        type: "optical",
        num_layer: 2,
        step: 70,
        micro_step: 80,
        z_axis: 14,
        condenser: null,
        brightness: null,
        magnification: 100,
        description:
          "Fugit reprehenderit ab ut non aspernatur explicabo eum in.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:09.000000Z",
        updated_at: "2024-01-24T13:55:09.000000Z",
      },
    },
    {
      id: 3,
      patient_id: 30,
      lab_id: 58,
      test_type_id: 18,
      sender_register_code: "518",
      doctor_name: "Stone Lynch Sr.",
      price: 114076,
      status: "scanning",
      num_slide: 1,
      duration: 71,
      description:
        "Est consequatur velit occaecati laboriosam consequatur aut tempore ea distinctio possimus sunt et et non cumque magnam sequi.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 18,
        title: "consequuntur",
        code: "647",
        gender: "female",
        type: "fluorescent",
        num_layer: 1,
        step: null,
        micro_step: null,
        z_axis: null,
        condenser: null,
        brightness: 77,
        magnification: 10,
        description:
          "Nostrum voluptas eligendi quam recusandae ratione aut fugiat voluptates tempora eligendi eveniet omnis.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:09.000000Z",
        updated_at: "2024-01-24T13:55:09.000000Z",
      },
    },
    {
      id: 4,
      patient_id: 52,
      lab_id: 23,
      test_type_id: 8,
      sender_register_code: "896",
      doctor_name: "Mr. Emery Steuber II",
      price: 236837,
      status: "answered",
      num_slide: 1,
      duration: 17,
      description:
        "Et reiciendis minima explicabo veniam et id similique voluptatem vel molestiae illum et mollitia et.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 8,
        title: "voluptas",
        code: "213",
        gender: "both",
        type: "fluorescent",
        num_layer: 3,
        step: 21,
        micro_step: 29,
        z_axis: null,
        condenser: null,
        brightness: null,
        magnification: 40,
        description:
          "A tenetur velit et quis alias commodi qui nisi amet repellat unde.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:08.000000Z",
        updated_at: "2024-01-24T13:55:08.000000Z",
      },
    },
    {
      id: 5,
      patient_id: 100,
      lab_id: 52,
      test_type_id: 24,
      sender_register_code: "818",
      doctor_name: "Prof. Faye Feest",
      price: 315841,
      status: "scanned",
      num_slide: 3,
      duration: 45,
      description:
        "Ullam deleniti veniam cumque expedita hic quis eos eum autem eius quam esse non.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 24,
        title: "exercitationem",
        code: "382",
        gender: "both",
        type: "invert",
        num_layer: 3,
        step: 82,
        micro_step: 27,
        z_axis: null,
        condenser: 49,
        brightness: null,
        magnification: 10,
        description:
          "Repellendus repudiandae inventore mollitia eos dolore molestiae impedit non vel voluptatem.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:09.000000Z",
        updated_at: "2024-01-24T13:55:09.000000Z",
      },
    },
    {
      id: 6,
      patient_id: 37,
      lab_id: 70,
      test_type_id: 15,
      sender_register_code: "344",
      doctor_name: "Emilio Stoltenberg",
      price: 256166,
      status: "scanning",
      num_slide: 3,
      duration: 61,
      description:
        "Ut praesentium fugit voluptatum mollitia animi deleniti corporis et est.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 15,
        title: "eaque",
        code: "278",
        gender: "both",
        type: "fluorescent",
        num_layer: 2,
        step: 48,
        micro_step: 91,
        z_axis: null,
        condenser: 36,
        brightness: null,
        magnification: 40,
        description:
          "Eos voluptas quae quod dolore magnam esse aspernatur facere facilis tempora.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:09.000000Z",
        updated_at: "2024-01-24T13:55:09.000000Z",
      },
    },
    {
      id: 7,
      patient_id: 16,
      lab_id: 33,
      test_type_id: 28,
      sender_register_code: "605",
      doctor_name: "Gladyce Schowalter",
      price: 187862,
      status: "answered",
      num_slide: 1,
      duration: 72,
      description:
        "Porro quidem ex nisi libero quos voluptates ipsum eos qui iusto aut repudiandae atque quis aut ab quidem nam.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 28,
        title: "dolores",
        code: "588",
        gender: "both",
        type: "optical",
        num_layer: 2,
        step: 65,
        micro_step: 64,
        z_axis: 50,
        condenser: null,
        brightness: null,
        magnification: 100,
        description:
          "Tempore unde nostrum ipsum maiores enim eveniet id dolorum quaerat rerum repudiandae pariatur exercitationem.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:09.000000Z",
        updated_at: "2024-01-24T13:55:09.000000Z",
      },
    },
    {
      id: 8,
      patient_id: 61,
      lab_id: 8,
      test_type_id: 23,
      sender_register_code: "329",
      doctor_name: "Thomas Connelly V",
      price: 172633,
      status: "answered",
      num_slide: 2,
      duration: 74,
      description:
        "Qui perferendis perferendis dolore ab unde sequi vitae corporis aspernatur quis qui quo iste molestiae numquam esse architecto.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 23,
        title: "ut",
        code: "334",
        gender: "male",
        type: "invert",
        num_layer: 3,
        step: 81,
        micro_step: 21,
        z_axis: 78,
        condenser: 32,
        brightness: null,
        magnification: 2,
        description:
          "Cumque explicabo alias voluptas occaecati et dolore molestiae a repudiandae.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:09.000000Z",
        updated_at: "2024-01-24T13:55:09.000000Z",
      },
    },
    {
      id: 9,
      patient_id: 13,
      lab_id: 24,
      test_type_id: 12,
      sender_register_code: "773",
      doctor_name: "Dr. Trycia Pagac",
      price: 174768,
      status: "scanned",
      num_slide: 1,
      duration: 56,
      description:
        "Ipsam excepturi exercitationem ab omnis omnis quo illum pariatur soluta quas aut sed reprehenderit aut dolorem.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 12,
        title: "omnis",
        code: "428",
        gender: "female",
        type: "fluorescent",
        num_layer: 3,
        step: 82,
        micro_step: 31,
        z_axis: null,
        condenser: 41,
        brightness: null,
        magnification: 100,
        description:
          "Cumque similique quis ut quod saepe est ut et totam dolorum debitis eius.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:08.000000Z",
        updated_at: "2024-01-24T13:55:08.000000Z",
      },
    },
    {
      id: 10,
      patient_id: 84,
      lab_id: 27,
      test_type_id: 2,
      sender_register_code: "115",
      doctor_name: "Edgar Yundt",
      price: 118540,
      status: "answered",
      num_slide: 2,
      duration: 95,
      description:
        "Suscipit consequuntur quaerat minima occaecati totam sed et quas nihil suscipit quae praesentium illum.",
      created_at: "2024-01-25T14:15:38.000000Z",
      updated_at: "2024-01-25T14:15:38.000000Z",
      test_type: {
        id: 2,
        title: "ea",
        code: "432",
        gender: "male",
        type: "optical",
        num_layer: 1,
        step: null,
        micro_step: null,
        z_axis: 11,
        condenser: null,
        brightness: null,
        magnification: 100,
        description:
          "Consequuntur eos eos est quibusdam omnis id optio ut tempore ut.",
        deleted_at: null,
        created_at: "2024-01-24T13:55:08.000000Z",
        updated_at: "2024-01-24T13:55:08.000000Z",
      },
    },
  ],
  first_page_url: "http://localhost:8000/api/registration?page=1",
  from: 1,
  last_page: 10,
  last_page_url: "http://localhost:8000/api/registration?page=10",
  links: [
    { url: null, label: "&laquo; Previous", active: false },
    {
      url: "http://localhost:8000/api/registration?page=1",
      label: "1",
      active: true,
    },
    {
      url: "http://localhost:8000/api/registration?page=2",
      label: "2",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=3",
      label: "3",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=4",
      label: "4",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=5",
      label: "5",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=6",
      label: "6",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=7",
      label: "7",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=8",
      label: "8",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=9",
      label: "9",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=10",
      label: "10",
      active: false,
    },
    {
      url: "http://localhost:8000/api/registration?page=2",
      label: "Next &raquo;",
      active: false,
    },
  ],
  next_page_url: "http://localhost:8000/api/registration?page=2",
  path: "http://localhost:8000/api/registration",
  per_page: 10,
  prev_page_url: null,
  to: 10,
  total: 100,
};
